# Extracted data from DICOM files
KEYS = {
    "Patient": "PatientID",
    "BodyPartExamined": "BodyPartExamined",
    "ImagePositionPatient": "ImagePositionPatient",
    "ImageOrientationPatient": "ImageOrientationPatient",
    "PhotometricInterpretation": "PhotometricInterpretation",
    "Rows": "Rows",
    "Columns": "Columns",
    "PixelSpacing": "PixelSpacing",
    "WindowCenter": "WindowCenter",
    "WindowWidth": "WindowWidth",
    "Modality": "Modality",
    "StudyInstanceUID": "StudyInstanceUID",
    "SeriesInstanceUID": "SeriesInstanceUID",
    "StudyID": "StudyID",
    "SamplesPerPixel": "SamplesPerPixel",
    "BitsAllocated": "BitsAllocated",
    "BitsStored": "BitsStored",
    "HighBit": "HighBit",
    "PixelRepresentation": "PixelRepresentation",
    "RescaleIntercept": "RescaleIntercept",
    "RescaleSlope": "RescaleSlope",
    "img_min": "img_min",
    "img_max": "img_max",
    "img_mean": "img_mean",
    "img_std": "img_std",
}
